# Generated by Django 5.0.6 on 2024-05-21 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Car Type')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_license_plate', models.CharField(max_length=30, unique=True, verbose_name='License Plate')),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='htmx_tests.cartype')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='htmx_tests.city')),
            ],
        ),
        migrations.CreateModel(
            name='CarPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='htmx_tests.car')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='htmx_tests.city')),
            ],
        ),
    ]
