# Generated by Django 5.0.6 on 2024-05-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmx_tests', '0002_employee_resturant_emppool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emppool',
            name='resturant',
            field=models.ManyToManyField(blank=True, to='htmx_tests.resturant'),
        ),
    ]
