# Generated by Django 5.0.6 on 2024-06-03 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htmx_tests', '0007_alter_ordersummary_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='place',
            new_name='location',
        ),
    ]
